workflows:
  vlaw-ios-staging:
    name: vlaw ios staging
    max_build_duration: 60
    environment:
      node: 14.20.0
      npm: 6.14.17
      groups:
      - staging
    scripts:
    - name: Building ios app
      script: |
       npm run build:web
       npm run build:cordova:ios:release:staging:law