workflows:
  ios-workflow:
    name: Build iOS Cordova App
    instance_type: mac_mini_m2
    max_build_duration: 100
    environment:
      vars: 
        ANDROID_NDK_VERSION: "21.3.6528147"
        GOOGLE_PLAY_TRACK: "beta"
      groups:
      - keystore_credentials
      - app_store_credentials        
      flutter: stable
      xcode: latest  # Версия Xcode, например, latest
      cocoapods: 1.9.1
      node: 16.20.0  # Версия Node.js
      npm: 6.13.7
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
        - pattern: develop
          include: false
        - pattern: feature-1
          include: true
          source: true
    scripts:
      # Установка Cordova и зависимостей
      - name: Install Cordova and dependencies
        script: |
          npm install -g cordova  # Устанавливаем Cordova глобально
          npm install  # Устанавливаем зависимости вашего проекта, если есть package.json

      # Сборка приложения с помощью Cordova
      - name: Build iOS with Cordova
        script: |
          cordova platform add ios  # Добавляем платформу iOS
          cordova build ios --release  # Собираем проект для iOS (релизная версия)
          
    artifacts:
      # Указываем путь к артефактам сборки (в данном случае .ipa файл для iOS)
      - platforms/ios/build/device/*.ipa
